### ISSUE TITLE
Error in yaml::yaml.load(enc2utf8(string), ...) : Reader error: control characters are not allowed: #81 at 276

### ISSUE THREAD

**Issue by englianhu** [viking/r-yaml#31] opened 2016-08-28 07:34 UTC
By refer to https://github.com/rstudio/rsconnect/issues/115, I unable publish shinyapp to RStudio Connect. https://github.com/ramnathv/slidify/issues/417 faced similar YAML encoding error.

Error: #81 at 276 line while line `#'@ list(lm5, lm6, lm7, lm8, lm9, lm10, lm11, lm12) %>% llply(stargazer, anova, type = 'html')` just a comment codes.

**Comment by englianhu** [comment] 2016-09-06 19:11
By refer to https://github.com/rstudio/rsconnect/issues/115#issuecomment-244440798, I traced the source of error and updated the packages.

[YAML header error.txt](https://github.com/viking/r-yaml/files/457544/YAML.header.error.txt)

However the error is keeping there when I completed knitting, **even worse the outcome became blank page** and the publish button prompt me below errors:

![image](https://cloud.githubusercontent.com/assets/7227582/18287216/24ef2716-74b1-11e6-9efa-15ec9725889f.png)

![image](https://cloud.githubusercontent.com/assets/7227582/18287197/14b07594-74b1-11e6-89a4-18fefca8f3b4.png)

```diff
- Error in yaml::yaml.load(enc2utf8(string), ...) : 
-   Reader error: control characters are not allowed: #81 at 275
- Error in yaml::yaml.load(enc2utf8(string), ...) : 
-   Reader error: control characters are not allowed: #81 at 275
- Error in yaml::yaml.load(enc2utf8(string), ...) : 
-   Reader error: control characters are not allowed: #81 at 275
```

**Comment by viking** [comment] 2017-02-28 21:11
I'm not able to reproduce your error. I can load your file without any problems.

**Comment by Eflores89** [comment] 2017-07-20 17:13
I have a very similar issue. Did you get it to work @englianhu ?

**Comment by raviolli77** [comment] 2017-07-21 17:33
Currently getting the same error when using the rmarkdowntemplates package. Any help is appreciated!

**Comment by viking** [comment] 2017-11-08 19:16
This seems to be fixed in master now.

**Closed by viking** 2017-11-08 19:17 UTC
