### ISSUE TITLE
"foo: y" incorrectly interpreted as boolean

### ISSUE THREAD

**Issue by zachmayer** [viking/r-yaml#24] opened 2015-08-19 16:18 UTC
According to [the yaml spec](https://en.wikipedia.org/wiki/YAML#Data_types) "Yes" is the boolean data type.  The yaml package incorrectly also interprets "y" as boolean.
pyaml output:
```{python}
>>> import yaml
>>> yaml.load("Target: y")
{'Target': 'y'}
```

Incorrect r-yaml output:
```{R}
> yaml.load('Target: y')
$Target
[1] TRUE
```

**Comment by zachmayer** [comment] 2015-08-19 16:22
I stand corrected: http://yaml.org/type/bool.html

Looks like the pyaml author went with a stricter definition.

**Comment by zachmayer** [comment] 2015-08-19 16:27
Here's a bigger test case of possible booleans:
```{R}
y <- yaml.load('a: Y
b: yes
c: Yes
d: YES
e: n
f: N
g: no
h: No
i: NO
j: true
k: True
l: TRUE
m: false
n: False
o: FALSE
p: on
q: On
r: ON
s: off
t: Off
u: OFF')
```

Which returns:
```{R}
> unlist(y)
    a     b     c     d     e     f     g     h     i     j     k     l     m FALSE     o     p     q     r     s     t     u 
 TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE 
```

It seems there's one possible bug (though I'm not sure of this):
```{R}
yaml.load('n: False')
```

I think in this case, the "n" should remain an "n", rather than getting converted to a boolean then back to a string.

**Comment by viking** [comment] 2015-08-19 18:21
This is a duplicate of bug #5. Please see that bug.

Thanks.

**Closed by viking** 2015-08-19 18:21 UTC

**Comment by viking** [comment] 2015-08-19 18:29
As for your other question about loading "n: False", the result being `list('FALSE'=FALSE)` is intended. Please see the documentation for `yaml.load` for the behavior of named list results. Other languages (such as Ruby) also create `{false=>false}` for strings like "no: false". Ruby and Python may not convert "y" and "n" to boolean, but the YAML 1.1 specification indicates that they should be converted.

**Comment by zachmayer** [comment] 2015-08-19 18:31
Thanks for the info
