### ISSUE TITLE
Merge keys (cont)

### ISSUE THREAD

**Issue by MikeBadescu** [viking/r-yaml#65] opened 2018-09-08 17:46 UTC
I am not sure whether the merge keys fix (#58) is complete. The placement of the `<<:` should not matter as the `# Override` example in the [merge specification](http://yaml.org/type/merge.html) shows.

In the same example `y` keys are treated as TRUE by this package (which I suspect is a separate bug). I replaced `y` with `yy` to obtain the following result. In the last element `x` should have been `1` instead of `0`.

```r
> str(yaml::yaml.load_file("merge.yml"))
Warning in yaml.load(readLines(con), error.label = error.label, ...) :
  Duplicate map key ignored during merge: 'r'
List of 8
 $ :List of 2
  ..$ x : int 1
  ..$ yy: int 2
 $ :List of 2
  ..$ x : int 0
  ..$ yy: int 2
 $ :List of 1
  ..$ r: int 10
 $ :List of 1
  ..$ r: int 1
 $ :List of 4
  ..$ x    : int 1
  ..$ yy   : int 2
  ..$ r    : int 10
  ..$ label: chr "center/big"
 $ :List of 4
  ..$ x    : int 1
  ..$ yy   : int 2
  ..$ r    : int 10
  ..$ label: chr "center/big"
 $ :List of 4
  ..$ x    : int 1
  ..$ yy   : int 2
  ..$ r    : int 10
  ..$ label: chr "center/big"
 $ :List of 4
  ..$ r    : int 10
  ..$ x    : int 0
  ..$ yy   : int 2
  ..$ label: chr "center/big"
```

Also, I think that there should not be a warning for duplicate keys.

**Comment by viking** [comment] 2018-09-10 16:54
I'll take a look.

**Comment by viking** [comment] 2018-09-13 15:16
Converting 'y' to true is not a bug, it's expected. Please see the discussion here: #5. The string 'y' is canonically treated as a boolean value.

The merge key specification is contradictory. It states that maps that are merged are done so in order, and earlier values override later ones. For the last example, the 'LEFT' alias contains an 'x' value of 0. This occurs _before_ the later `x: 1` string in the map. I interpreted the specification to mean that earlier key-value pairs always override later ones.

**Comment by viking** [comment] 2018-09-13 15:33
I know there are other languages that allow non-merge map key-value pairs to override earlier key-value pairs that were merged. However, the specification is less than clear about this situation. There's an argument to be made about having the same behavior as other major programming languages, though.

**Comment by MikeBadescu** [comment] 2018-09-13 16:51
Thank you for looking into this.

When the merge key is a sequence, the merging *within the sequence* works as expected. In the last example, `*BIG r:10`  overrides `*SMALL r:1`. 

The issue is the merging of  `*LEFT x:0` with `x:1`. I agree that the wording of the specification is not clear. My suggested change is based on the doc example and, as you remarked, the behavior in other programming languages. I think it nice to have close to 100% compatibility with Python (PyYAML)  and maybe others (if possible) as it helps switching data pipelines / apps from one language to another.

Maybe adding an option `string_merge = FALSE` would help? This way the default behavior would be similar to other prog languages and there is an option for strict merging.

**Comment by viking** [comment] 2018-09-13 20:07
Yeah, that seems like a reasonable course of action. I've thought about removing the warnings in the past, too, but being more verbose seemed like erring on the side of caution. I could add another option for whether to warn about conflicting key-value pairs.

**Comment by viking** [comment] 2018-09-13 21:04
So it turns out that order seems to matter for some implementations. Check out the result of parsing the merge file and moving the last merge at the bottom:

Ruby:
```ruby
[{"x"=>1, "y"=>2}, {"x"=>0, "y"=>2}, {"r"=>10}, {"r"=>1}, {"x"=>1, "y"=>2, "r"=>10, "label"=>"center/big"}, {"x"=>1, "y"=>2, "r"=>10, "label"=>"center/big"}, {"r"=>10, "x"=>1, "y"=>2, "label"=>"center/big"}, {"x"=>0, "label"=>"center/big", "r"=>10, "y"=>2}]
```

Python:
```python
[{'x': 1, 'y': 2}, {'x': 0, 'y': 2}, {'r': 10}, {'r': 1}, {'x': 1, 'y': 2, 'r': 10, 'label': 'center/big'}, {'x': 1, 'y': 2, 'r': 10, 'label': 'center/big'}, {'r': 10, 'x': 1, 'y': 2, 'label': 'center/big'}, {'r': 10, 'x': 1, 'y': 2, 'label': 'center/big'}]
```

**Comment by viking** [comment] 2018-09-13 21:16
This makes me hesitant to change the R package behavior since there is no real definitive answer on how merges should behave to override values.

**Comment by MikeBadescu** [comment] 2018-09-14 02:33
I see the issue. In my opinion, it would help to have the flexibility, e.g. a `python` flag.

**Comment by viking** [comment] 2018-09-14 14:49
That's not a bad idea. I could see this becoming tedious though. What if different versions of PyYAML behave differently? What if future versions behave differently? Not having a properly worded specification makes this sort of shaky ground.

I think instead of calling the flag `python` or `ruby`, the flag could be called something like `merge.precedence`.

**Comment by viking** [comment] 2018-11-01 17:13
I've add a `merge.precedence` parameter to `yaml.load`. If you set this to `"override"`, it will behave like Python does. I'm planning on adding a way to silence warnings about merges next.

**Comment by viking** [comment] 2018-11-14 16:59
I added a `merge.warning` parameter to yaml.load in https://github.com/viking/r-yaml/commit/3d8a726950b5a0c698e9d650bae26bfc17e32f6c. Pending some additional checks I think that about wraps up this issue.

**Comment by MikeBadescu** [comment] 2018-11-14 17:23
Thank you!

**Closed** 2018-11-27 22:04 UTC
